- hosts: all
  become: yes
  tasks:
    - name: alterando nome dos hosts
      hostname:
        name: '{{ new_hostname }}'
    # - name: instalando o apache
    #   apt: 
    #     name: apache2
    #     state: present
    #     update_cache: yes